server:
  port: 10000
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${gannon.spring.cloud.nacos.server-addr}
        username: ${gannon.spring.cloud.nacos.username}
        password: ${gannon.spring.cloud.nacos.password}
    gateway:
#      discovery:
#        locator:
#          开启从注册中心动态创建路由的功能，利用微服务名进行路由
#          enable: true
      routes:
        - id: cloud-user-consumerth1
#          http://localhost:9001/consumer/users/id/2
          uri: lb://cloud-user-consumer
          predicates:
#            http://localhost:10000/users/id/2
            - Path=/users/id/**
          filters:
            - PrefixPath=/consumer
        - id: cloud-user-consumerth2
          #          http://localhost:9001/consumer/users
          uri: lb://cloud-user-consumer
          predicates:
            #            http://localhost:10000/users/id/2
            - Path=/users
          filters:
            - PrefixPath=/consumer
        - id: cloud-user-consumerth3
            #          http://localhost:9001/consumer/users
          uri: lb://cloud-user-consumer
          predicates:
              #            http://localhost:10000/users/id/2
            - Path=/users/**
          filters:
            - PrefixPath=/consumer
#eureka:
#  client:
#    instance:
#      hostname: cloud-gateway-service
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka