server:
  port: 10000
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.11:8888
        username: nacos
        password: nacos
    gateway:
#      discovery:
#        locator:
#          开启从注册中心动态创建路由的功能，利用微服务名进行路由
#          enable: true
      routes:
        - id: cloud-user-providerth1
#          http://localhost:8001/provider/users/id/2
          uri: lb://cloud-user-provider
          predicates:
#            http://localhost:10000/users/id/2
            - Path=/users/id/**
          filters:
            - PrefixPath=/provider
#eureka:
#  client:
#    instance:
#      hostname: cloud-gateway-service
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka