server:
  port: 8888
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: cloud-user-consumer
          uri:
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka