server:
  port: 7002
spring:
  application:
    name: cloud-eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka