server:
  port: 8003
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@${gannon.database.server.host}:${gannon.database.server.port}:${gannon.database.server.sid}
    username: ${gannon.database.server.username}
    password: ${gannon.database.server.password}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 100
  jpg:
    show-sql: true
#集成Eureka注册中心
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:7002/eureka
logging:
  level:
    com:
      gannon:
        cloud: debug
