server:
  port: 9001
spring:
  application:
    name: cloud-user-consumer
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka