server:
  port: 8002
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@${gannon.database.server.host}:${gannon.database.server.port}:${gannon.database.server.sid}
    username: ${gannon.database.server.username}
    password: ${gannon.database.server.password}
    type: com.alibaba.druid.pool.DruidDataSource
#集成Eureka注册中心
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:7002/eureka
mybatis:
  mapper-locations: /mapper/*.xml
  type-aliases-package: com.gannon.cloud.dao
logging:
  level:
    com:
      gannon:
        cloud:
          dao: debug
